apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rollreviewer.fullname" . }}-secrets
  labels:
    {{- include "rollreviewer.labels" . | nindent 4 }}
type: Opaque
stringData:
  OC_RR_OIDC_CLIENT_SECRET: {{ .Values.backend.secrets.oidcClientSecret | quote }}
